# Docker compose start container with env variables
services:
  local-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=itjustworks
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"

  api-server:
    image: lms-public-api
    build: .
    environment:
      - MODE=local
      - PORT=8081
      - DATABASE_URL=postgresql://postgres:itjustworks@local-db:5432/mydb
    ports:
      - "8081:8081"
    depends_on:
      - local-db
